LEVEL_MAP = [
[[
'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
'B                               B',
'B          F                    B',
'B          5                    B',
'BF                              B',
'B2                              B',
'B                               B',
'B  231                     25555B',
'B           1              D I  B',
'B    P      B1       M          B',
'B434444551  BB354435443544532545B',
'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY'],
[
'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
'B                              FB',
'B                               B',
'B                               B',
'B               F               B',
'B        345345345345345        B',
'B                          25555B',
'B P                        D I  B',
'B33332         M                B',
'BBBBBB2    23332         2233333B',
'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY'],
[
'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
'B                                                     D I  B',
'B                5345345345                                B',
'B                         B 345                     3453453B',
'B                         B                     345        B',
'B         345             BCCCC 345         345            B',
'BM                        B F C                            B',
'B345                      BBBBB          5                 B',
'BBBB45                    B    54345345345345           H  B',
'BBBBBB45                  B                      3453453453B',
'BP     X                  B                                B',
'345345345345345   34534534B                                B',
'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY'],
[
'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
'B                             B                                B               F             B',
'B    P                        B                                B                             B',
'B345345345345  345345345345345B                                B                             B',
'BBBBBBBBBBBBB  BBBBBBBBBBBBBBBB                                B                             B',
'BBBBBBBBBBBBB  BBBBBBBBBBBBBBBB         23453453               B          345345345345       B',
'B      H    B  BBBBBBBBBBBBBBBB        2BBBBBBBB               B                             B',
'B           B  BBBBBBBBBBBBBBBB       2BBBBBBBBB               B                             B',
'B           X                 B      2BBBBBBBBBB                    M                   25555B',
'BBBBBBBBBBBBBBBBBBBBBBBBBBBB  B     2BBBBBBBBBBB       45345345345345345345             D I  B',
'B         F              CCC       2BBBBBBBBBBBB       BBBBBBBBBBBBBBBBBBBB                  B',
'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBBBB5345         345345',
'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY'],
[
'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
'B                          D I  B',
'B                               B',
'B                         134534B',
'B          X                   FB',
'B          X           544535454B',
'B          X                    B',
'B          X                    B',
'B    P     X                    B',
'B434444554453                   B',
'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY'],
[
'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
'B               F                          B                          B               D I  B',
'B                                          B                          B                    B',
'B                  534                     B                          B              134534B',
'B                       534                B              F           B                   FB',
'B                                          B                          B5445354545445354543CB',
'B                              34          B            35454        HBCCCCCCCCCCCCCCCCCCCCB',
'B                                                                35454BC5445354545445354543B',
'B                       534                                           BCCCCCCCCCCCCCCCCCCCCB',
'B5435              34       35454          B        544535454544535454B5445354545445354543CB',
'B    P                                     B        CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB',
'B4344445544534344              554453434444554453434444554453434444554453434444554453434444B',
'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY']
],
[[
'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
'B                               B',
'B          5                    B',
'BF                              B',
'B2  X        XXXX               B',
'B   X                      25345B',
'B  231                   D   I  B',
'B           1    X              B',
'B    PQ     B1 F    M X   253345B',
'B434444551  BB354435443544BBBBBBB',
'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY'],
[
'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
'BF                         D I  B',
'B                               B',
'B                         134534B',
'B          X                    B',
'B          X                    B',
'B          X                    B',
'B          X                    B',
'B    PQ    X                    B',
'B4344445544532354435443544535454B',
'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY'],
[
'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
'B                               B',
'B         555                   B',
'BF                              B',
'B2                              B',
'B                               B',
'B  231                        25B',
'B           1                 DIB',
'B    PQ     B1              2545B',
'B4344445541 BB35443544354453BBBBB',
'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY']
],[[
'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
'B                               B',
'B          5                    B',
'BF                              B',
'B2                              B',
'B                           2345B',
'B  231                      D I B',
'B           1                   B',
'B    PQR    B1      M       2545B',
'B434444551  BB35443544354453BBBBB',
'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY'],
[
'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
'B                               B',
'B          55                   B',
'BF                              B',
'B2                              B',
'B                               B',
'B  231                        25B',
'B           1                 DIB',
'B    PQR    B1              2545B',
'B4344445541 BB35443544354453BBBBB',
'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY'],
[
'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
'B PQR            B           F               B',
'B345345345  34535B        3453453            B',
'BBBBBBBBBB  BBBBBB                           B',
'B    H      BBBBBB                           B',
'B        X       B                           B',
'BBBBBBBBBBBBBBBB B  M                   24535B',
'BBBBBBBBBBBBBBBB BBBBBBBB               D I  B',
'B  F         CCC                             B',
'B345345345345345345345345345345  345345345345B',
'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY']
],[[
'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
'B                               B',
'B          55                   B',
'BF                              B',
'B2                              B',
'B                               B',
'B  231                        25B',
'B           1                 DIB',
'B    PQRS   B1              2545B',
'B4344445541 BB35443544354453BBBBB',
'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY'],
[
'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
'B PQRS           B           F               B',
'B345345345  34535B        3453453            B',
'BBBBBBBBBB  BBBBBB                           B',
'B    H      BBBBBB                           B',
'B        X       B                           B',
'BBBBBBBBBBBBBBBB B  M                        B',
'BBBBBBBBBBBBBBBB BBBBBBBB                    B',
'B  F         CCC                           DIB',
'B345345345345345345345345345345  345345345345B',
'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY'],
[
'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
'B                               B',
'B          55                   B',
'BF                              B',
'B2                              B',
'B                               B',
'B  231                        25B',
'B           1                 DIB',
'B    PQRS   B1              2545B',
'B4344445541 BB35443544354453BBBBB',
'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY'],
[
'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
'B                               B',
'B         555                   B',
'BF                              B',
'B2                              B',
'B                               B',
'B  231                        25B',
'B           1                 DIB',
'B    PQRS   B1              2545B',
'B4344445541 BB35443544354453BBBBB',
'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY']
]
]


TILE_SIZE = 64
SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768

# colors 
BG_COLOR = '#060C17'
PLAYER_COLOR = '#C4F7FF'
TILE_COLOR = '#94D7F2'

# camera
CAMERA_BORDERS = {
	'left': 100,
	'right': 200,
	'top':100,
	'bottom': 150
}